module: KituraSessionRedis
author: IBM and the Kitura project authors
github_url: https://github.com/Kitura/Kitura-Session-Redis/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Kitura-Session-Redis.xcodeproj, -target, KituraSessionRedis, LIBRARY_SEARCH_PATHS=.build/debug]
