branches:
  only:
    - master
    - develop
    - /^issue.*$/

notifications:
  slack:
    secure: "0U/dyR6r/xNppoytHDVUF4KYeiWSCTIl9m9WOIj/Z2uxbkgRPeGaAG7/5anEhu4A1G+f5Y4ZxP6lbKno47wa5dHQO/gRgworkJzSxq78/PuIRbvbvf/RLwXnrWDISQ7AOmnatfpkxePVh1LgRi5F+K3hNlHBBt5d3bEdiApsZVugAKZgycmoWdSjgc0UJXph6E5Go2N774N8yZlQ3mdTKMZmJlB1wm67wDcDw8VgQVoXZfDnZcT4YtdkFLb40fwMMppTxqukqM9UqFp3E4qr1oPvnDM0lUcK3PSWKjvGdA+YCbsntHowqpTwiDjKCA0OvL8ump3RTIjL9uWfHVCJ9fxU7U4PmmdEOR3jmDZZNcrEOaRSdaWIKkCk4uEMmLh3wBHyZ87wvXVYm8NZ//Z6ENEHDzZ5rhf+ypoDt+2T/R80rKlcgYmShF6lVbFF/zRFU99Gto8nUF4cSX+xIdgFWR4IVIW4V8n7C/Yoo+iWUNjdqutndveHS+msVvXMmo1ANLW4/G1QZvNDzcTJqXtuBkZWBn5+Kf2GhypmULxZQImYQPMuPFd+sY1XfNRHsL5ktebIYEyxLjk4H9b90CMB4N2UewK3UHngtjRuak+i8ayKK7LXh1MIAQkI0faZThvRnoOGJhMc5pThSpMLJpPrCDGWaIn7ceLayclWxFKSsd8="

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=4.0-DEVELOPMENT-SNAPSHOT-2017-06-29-a
    - os: osx
      osx_image: xcode8.3
      sudo: required
    - os: osx
      osx_image: xcode9
      sudo: required
      env: SWIFT_SNAPSHOT=4.0-DEVELOPMENT-SNAPSHOT-2017-06-29-a

before_install:
  - git clone https://github.com/IBM-Swift/Kitura-CI.git
  - git clone https://github.com/IBM-Swift/Package-Builder.git
  - test -n "$SWIFT_VERSION" && echo "$SWIFT_VERSION" > .swift-version || echo "SWIFT_VERSION not set, using $(cat .swift-version)"

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
